# Generated by Django 3.0.3 on 2020-03-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_datetime_at', models.DateTimeField()),
                ('organizer_name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('finish_datetime_at', models.DateTimeField(null=True)),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_max', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='TicketmasterScrapedRawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('url', models.URLField()),
                ('status_code', models.IntegerField()),
            ],
        ),
    ]
