# Generated by Django 3.0.3 on 2020-03-17 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='event_name',
        ),
    ]
