# Generated by Django 3.0.3 on 2020-03-17 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0002_auto_20200317_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organizer_name',
            new_name='promoter_name',
        ),
    ]
